version: "3.8"

services:

  api:
    build:
      context: ./api
      dockerfile: ./docker/nginx/Dockerfile
    container_name: api
    restart: unless-stopped
    volumes:
      - ./api:/var/www/app
      - ./api/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app_network

  php:
    build:
      context: ./api
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
      - ./api:/var/www/app
    ports:
      - "9000:9000"
    networks:
      - app_network

  client:
    build:
      context: ./client
      dockerfile: ./docker/nginx/Dockerfile
    container_name: client
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - ./client:/app
      - ./client/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    networks:
      - app_network

networks:
  app_network: