version: "3.8"

services:

  api:
    image: 01234ab909f/zadanie1-api:main
    container_name: api
    restart: unless-stopped
    platform: linux/amd64
    volumes:
      - ./api:/var/www/app
      - ./api/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app_network

  php:
    image: 01234ab909f/zadanie1-php:main
    container_name: php
    restart: unless-stopped
    platform: linux/amd64
    volumes:
      - ./api:/var/www/app
    ports:
      - "9000:9000"
    networks:
      - app_network

  client:
    image: 01234ab909f/zadanie1-client:main
    container_name: client
    restart: unless-stopped
    platform: linux/amd64
    volumes:
      - /app/node_modules
      - ./client:/app
      - ./client/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    networks:
      - app_network

networks:
  app_network: