ARG PHP_VERSION=8.0.26

FROM php:${PHP_VERSION}-fpm-buster

COPY /docker/php/php.ini /usr/local/etc/php/

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/app